Repository sbondCo/Watcharr, pull requests merged in 2023-08, with the labels that each got.

#63 Themes
  package-lock.json
  package.json
  src/lib/Activity.svelte
  src/lib/PersonPoster.svelte
  src/lib/Poster.svelte
  src/lib/Rating.svelte
  src/lib/Spinner.svelte
  src/lib/Status.svelte
  src/lib/util/helpers.ts
  src/norm.scss
  src/routes/(app)/+layout.svelte
  src/routes/(app)/movie/[id]/+page.svelte
  src/routes/(app)/profile/+page.svelte
  src/routes/(app)/tv/[id]/+page.svelte
  src/routes/+layout.svelte
  src/store.ts
  src/types.ts
  src/vars.scss
  svelte.config.js
Labels: enhancement

#64 Make profile page responsive
  src/routes/(app)/profile/+page.svelte
Labels: bug

#69 Add thoughts to watched & Show notifications on added/updated watched items
  server/activity.go
  server/watched.go
  src/lib/Activity.svelte
  src/lib/Poster.svelte
  src/lib/Status.svelte
  src/lib/util/api.ts
  src/norm.scss
  src/routes/(app)/movie/[id]/+page.svelte
  src/routes/(app)/tv/[id]/+page.svelte
  src/types.ts
Labels: enhancement

#73 Show content rating
  src/lib/content/Title.svelte
  src/routes/(app)/movie/[id]/+page.svelte
  src/routes/(app)/tv/[id]/+page.svelte
Labels: enhancement

#74 Episode ratings
  src/lib/Activity.svelte
  src/lib/SeasonsList.svelte
Labels: bug, enhancement

#76 Trailers
  server/content.go
  server/routes.go
  server/tmdb.go
  src/lib/content/VideoEmbedModal.svelte
  src/routes/(app)/movie/[id]/+page.svelte
  src/routes/(app)/tv/[id]/+page.svelte
  src/types.ts
Labels: enhancement

#77 Fix episode ratings color
  src/lib/SeasonsList.svelte
  src/vars.scss
Labels: bug

#88 Update Client And Server Dependencies
  .eslintrc.cjs
  .prettierrc
  package-lock.json
  package.json
  server/go.mod
  server/go.sum
  src/app.d.ts
  src/app.html
  src/lib/Poster.svelte
  src/lib/content/VideoEmbedModal.svelte
  src/norm.scss
  src/types.ts
  tsconfig.json
Labels: enhancement

#90 Show `TBD` if seasons not aired and no episodes message
  src/lib/SeasonsList.svelte
Labels: bug, enhancement

#92 Hide tv runtimes if not provided in episode_run_time array
  src/routes/(app)/tv/[id]/+page.svelte
Labels: bug

#95 Server Logging To File
  README.md
  server/.env.example
  server/activity.go
  server/auth.go
  server/content.go
  server/go.mod
  server/go.sum
  server/profile.go
  server/tmdb.go
  server/watcharr.go
  server/watched.go
  src/lib/SeasonsList.svelte
Labels: enhancement

#97 Streaming Providers shown for content
  server/content.go
  server/tmdb.go
  src/lib/Icon.svelte
  src/routes/(app)/movie/[id]/+page.svelte
  src/routes/(app)/tv/[id]/+page.svelte
  src/types.ts
Labels: enhancement

#101 Play In Jellyfin / Providers
  server/auth.go
  server/content.go
  server/jellyfin.go
  server/middleware.go
  server/routes.go
  server/tmdb.go
  server/watcharr.go
  src/lib/Icon.svelte
  src/lib/content/ProviderIcon.svelte
  src/lib/content/ProvidersList.svelte
  src/lib/util/api.ts
  src/routes/(app)/movie/[id]/+page.svelte
  src/routes/(app)/tv/[id]/+page.svelte
  src/routes/(plain)/login/+page.svelte
  src/types.ts
Labels: bug, enhancement

#104 Support disabling signup
  README.md
  server/.env.example
  server/auth.go
  server/routes.go
  src/routes/(plain)/login/+page.svelte
  src/types.ts
Labels: enhancement

#105 Show a better empty watched list message
  src/lib/Icon.svelte
  src/routes/(app)/+page.svelte
  src/types.ts
Labels: enhancement

#106 Fade out content backdrop
  src/routes/(app)/movie/[id]/+page.svelte
  src/routes/(app)/tv/[id]/+page.svelte
  src/vars.scss
Labels: enhancement

#109 Discover
  server/content.go
  server/routes.go
  server/tmdb.go
  src/lib/Icon.svelte
  src/lib/Poster.svelte
  src/lib/PosterList.svelte
  src/lib/util/api.ts
  src/lib/util/helpers.ts
  src/routes/(app)/+layout.svelte
  src/routes/(app)/+page.svelte
  src/routes/(app)/discover/+page.svelte
  src/routes/(app)/profile/+page.svelte
  src/routes/(app)/search/[query]/+page.svelte
  src/routes/(app)/search/[query]/+page.ts
  src/types.ts
Labels: enhancement

#110 New sorting options: Rating, Last Changed
  src/lib/util/api.ts
  src/routes/(app)/+layout.svelte
  src/routes/(app)/+page.svelte
  src/types.ts
Labels: enhancement

#115 SeasonsList: Stop requesting season 1 twice
  src/lib/SeasonsList.svelte
Labels: bug

#116 Support using custom TMDB_KEY
  README.md
  server/.env.example
  server/tmdb.go
  server/watcharr.go
Labels: enhancement

#111 add year to Poster
  src/lib/Poster.svelte
  src/routes/(app)/+page.svelte
  src/types.ts
Labels: enhancement

#119 TMDB Request Caching
  server/go.mod
  server/go.sum
  server/routes.go
Labels: enhancement

#120 PersonPoster: Fix white flash on hover
  src/lib/PersonPoster.svelte
Labels: bug

#122 Loading Notifications
  src/lib/Activity.svelte
  src/lib/SpinnerTiny.svelte
  src/lib/util/api.ts
  src/lib/util/notify.ts
  src/norm.scss
  src/routes/(plain)/login/+page.svelte
  src/routes/+layout.svelte
  src/store.ts
Labels: enhancement

#123 Content: Omit ReleaseDate if not set
  server/content.go
  server/watched.go
  src/lib/Poster.svelte
Labels: bug

#125 Socialize - Allow viewing other watchlists
  server/auth.go
  server/routes.go
  server/user.go
  server/watcharr.go
  server/watched.go
  src/lib/Checkbox.svelte
  src/lib/Poster.svelte
  src/lib/UsersList.svelte
  src/lib/WatchedList.svelte
  src/lib/util/api.ts
  src/lib/util/helpers.ts
  src/norm.scss
  src/routes/(app)/+layout.svelte
  src/routes/(app)/+page.svelte
  src/routes/(app)/lists/[id]/[username]/+page.svelte
  src/routes/(app)/lists/[id]/[username]/+page.ts
  src/routes/(app)/profile/+page.svelte
  src/routes/(app)/search/[query]/+page.svelte
  src/routes/+layout.svelte
  src/store.ts
  src/types.ts
  src/vars.scss
Labels: enhancement
