Repository sbondCo/Watcharr, pull requests merged in 2024-07, with the labels that each got.

#573 doc: Create backup guide
  doc/docs/server_config/backup.md
Labels: documentation

#583 job: support adding unique jobs (by name)
  server/import_trakt.go
  server/jobs.go
  src/lib/JobWatcherModal.svelte
Labels: enhancement

#578 Fixed unit oversight
  src/lib/SeasonsListEpisode.svelte
Labels: bug
