Repository sbondCo/Watcharr, pull requests merged in 2024-03, with the labels that each got.

#394 Jellyfin (Manual) Sync
  server/activity.go
  server/jellyfin.go
  server/jellyfin_sync.go
  server/jobs.go
  server/routes.go
  server/watcharr.go
  server/watched.go
  server/watched_episodes.go
  server/watched_seasons.go
  src/lib/Activity.svelte
  src/routes/(app)/profile/+page.svelte
  src/routes/(app)/profile/modals/JellyfinSyncModal.svelte
  src/types.ts
Labels: enhancement

#395 Jellyfin sync improvements
  server/jellyfin_sync.go
  server/watched_episodes.go
  server/watched_seasons.go
  src/lib/Activity.svelte
  src/lib/util/helpers.ts
Labels: enhancement

#398 Add `restart` property to docker-compose example
  .gitignore
  doc/docs/installation/docker-compose.md
  docker-compose.yml
Labels: documentation

#399 Config: Don't omit SIGNUP_ENABLED when empty
  server/config.go
Labels: bug

#387 Issue #358 - Plex Oauth
  package-lock.json
  package.json
  server/auth.go
  server/config.go
  server/routes.go
  src/lib/Icon.svelte
  src/norm.scss
  src/routes/(app)/profile/+page.svelte
  src/routes/(app)/server/+page.svelte
  src/routes/(plain)/login/+page.svelte
  src/types.ts
  src/vars.scss
Labels: enhancement

#402 plex auth improvements
  package-lock.json
  package.json
  server/auth.go
  server/config.go
  server/plex.go
  server/routes.go
  src/lib/Icon.svelte
  src/lib/Status.svelte
  src/lib/util/plex.ts
  src/norm.scss
  src/routes/(app)/server/+page.svelte
  src/routes/(plain)/login/+page.svelte
  src/types.ts
  src/vars.scss
Labels: enhancement

#413 Plex sync
  server/activity.go
  server/auth.go
  server/jellyfin_sync.go
  server/plex.go
  server/plex_sync.go
  server/routes.go
  server/watcharr.go
  src/lib/Activity.svelte
  src/routes/(app)/profile/+page.svelte
  src/routes/(app)/profile/modals/SyncModal.svelte
  src/routes/(plain)/login/+page.svelte
  src/types.ts
Labels: enhancement

#415 Jobs: Fix getting job when id includes a slash (/)
  server/routes.go
Labels: bug

#423 Configurable data location
  server/config.go
  server/content.go
  server/watcharr.go
Labels: enhancement

#428 Posters and Search mobile responsiveness fixes
  src/lib/poster/Poster.svelte
  src/lib/poster/PosterList.svelte
  src/routes/(app)/+layout.svelte
Labels: bug, enhancement

#432 docs: installation for development
  doc/docs/installation/for-development.md
  doc/docs/installation/img/forking-repo.png
Labels: documentation

#437 User management
  server/arr.go
  server/auth.go
  server/config.go
  server/routes.go
  server/user_manage.go
  src/norm.scss
  src/routes/(app)/+layout.svelte
  src/routes/(app)/import/process/+page.svelte
  src/routes/(app)/manage_users/+page.svelte
  src/routes/(app)/manage_users/modals/EditUserModal.svelte
  src/routes/(app)/server/+page.svelte
  src/routes/(app)/server/modals/TwitchModal.svelte
  src/types.ts
Labels: enhancement

#389 Issue #130 - Import Watcharr Exports
  server/import.go
  src/routes/(app)/import/+page.svelte
  src/routes/(app)/import/process/+page.svelte
  src/store.ts
  src/types.ts
Labels: enhancement

#439 Importing from MyAnimeList
  doc/docs/importing/_category_.json
  doc/docs/importing/img/mal/export.png
  doc/docs/importing/myanimelist.md
  src/lib/WatchedList.svelte
  src/lib/poster/GamePoster.svelte
  src/lib/poster/Poster.svelte
  src/routes/(app)/+layout.svelte
  src/routes/(app)/import/+page.svelte
  src/routes/(app)/import/process/+page.svelte
  src/routes/(app)/person/[id]/+page.svelte
  src/routes/(app)/search/[query]/+page.svelte
  src/store.ts
Labels: enhancement

#445 docs: Environment Variables
  doc/docs/server_config/environment-variables.md
Labels: documentation
