Repository sbondCo/Watcharr, pull requests merged in 2024-04, with the labels that each got.

#474 Arr progress
  server/arr/arr.go
  server/arr/structs.go
  server/arr_queue.go
  server/arr_requests.go
  server/arr_requests_manage.go
  server/auth.go
  server/content.go
  server/routes.go
  server/tasks.go
  server/watcharr.go
  server/watched.go
  src/lib/Icon.svelte
  src/lib/SpinnerTiny.svelte
  src/lib/actions/tooltip.ts
  src/lib/request/ArrRequestButton.svelte
  src/lib/request/RequestMovie.svelte
  src/lib/request/RequestShow.svelte
  src/lib/util/helpers.ts
  src/routes/(app)/+layout.svelte
  src/routes/(app)/arr_requests/+page.svelte
  src/routes/(app)/manage_users/modals/EditUserModal.svelte
  src/routes/(app)/movie/[id]/+page.svelte
  src/routes/(app)/tv/[id]/+page.svelte
  src/types.ts
  src/vars.scss
Labels: enhancement

#463 Ability to set a country, both in server and user settings, to have the correct streaming provider (but doesn't affect language)
  server/auth.go
  server/config.go
  server/content.go
  server/middleware.go
  server/routes.go
  server/tmdb.go
  server/user.go
  src/lib/DropDown.svelte
  src/lib/RegionDropDown.svelte
  src/routes/(app)/movie/[id]/+page.svelte
  src/routes/(app)/profile/+page.svelte
  src/routes/(app)/server/+page.svelte
  src/routes/(app)/tv/[id]/+page.svelte
  src/types.ts
Labels: enhancement

#478 ProvidersList: Also display free providers
  src/lib/content/ProviderIcon.svelte
  src/lib/content/ProvidersList.svelte
Labels: bug, enhancement

#479 Sort by last finished/played
  src/lib/Icon.svelte
  src/lib/WatchedList.svelte
  src/lib/nav/FilterMenu.svelte
  src/lib/nav/SortMenu.svelte
  src/routes/(app)/+layout.svelte
Labels: enhancement

#485 import: Fix customDates all coming back the same in all activity
  server/import.go
Labels: bug

#486 Add delete button to content pages
  src/lib/Icon.svelte
  src/routes/(app)/game/[id]/+page.svelte
  src/routes/(app)/movie/[id]/+page.svelte
  src/routes/(app)/tv/[id]/+page.svelte
Labels: enhancement

#487 Games: Fix not able to add games previously removed from list
  server/games.go
Labels: bug

#494 LastFinished Sort: Use customDate, use updatedAt as fallback
  src/lib/WatchedList.svelte
Labels: bug

#495 Better thoughts
  src/lib/Rating.svelte
  src/lib/content/MyThoughts.svelte
  src/lib/util/api.ts
  src/routes/(app)/game/[id]/+page.svelte
  src/routes/(app)/movie/[id]/+page.svelte
  src/routes/(app)/tv/[id]/+page.svelte
Labels: enhancement

#496 Improve search (filters, remove dumb sort)
  src/lib/Icon.svelte
  src/routes/(app)/search/[query]/+page.svelte
  src/types.ts
Labels: enhancement

#497 Support detailed view on search page
  src/lib/WatchedList.svelte
  src/lib/nav/DetailedMenu.svelte
  src/lib/poster/Poster.svelte
  src/lib/util/helpers.ts
  src/routes/(app)/+layout.svelte
Labels: enhancement

#498 Support pinning watched list items to top
  server/watched.go
  src/lib/Icon.svelte
  src/lib/WatchedList.svelte
  src/lib/poster/GamePoster.svelte
  src/lib/poster/Poster.svelte
  src/lib/util/api.ts
  src/routes/(app)/game/[id]/+page.svelte
  src/routes/(app)/movie/[id]/+page.svelte
  src/routes/(app)/tv/[id]/+page.svelte
  src/types.ts
Labels: enhancement

#499 Content Pages: Make btns container wrap elements when overflowing
  src/routes/(app)/game/[id]/+page.svelte
  src/routes/(app)/movie/[id]/+page.svelte
  src/routes/(app)/tv/[id]/+page.svelte
Labels: bug

#504 Support emby branding
  server/auth.go
  server/config.go
  server/routes.go
  src/lib/Icon.svelte
  src/routes/(app)/profile/+page.svelte
  src/routes/(app)/profile/modals/SyncModal.svelte
  src/routes/(app)/server/+page.svelte
  src/routes/(app)/tv/[id]/+page.svelte
  src/routes/(plain)/login/+page.svelte
  src/types.ts
Labels: enhancement
