Repository sbondCo/Watcharr, pull requests merged in 2024-02, with the labels that each got.

#334 Movary Importing
  server/activity.go
  server/import.go
  server/watched.go
  src/lib/Activity.svelte
  src/lib/DropFileButton.svelte
  src/lib/Icon.svelte
  src/routes/(app)/import/+page.svelte
  src/routes/(app)/import/process/+page.svelte
  src/store.ts
  src/types.ts
Labels: enhancement

#335 https://github.com/sbondCo/Watcharr/issues/332#issuecomment-1923230972
  server/auth.go
  server/import.go
  server/user.go
  server/watched.go
  src/lib/WatchedList.svelte
  src/routes/(app)/import/+page.svelte
  src/routes/(app)/profile/+page.svelte
  src/types.ts
Labels: bug

#336 Fix movary importing and include previously watched filter
  server/auth.go
  server/import.go
  server/profile.go
  src/lib/WatchedList.svelte
  src/routes/(app)/profile/+page.svelte
Labels: bug

#343 Game docs
  doc/docs/server_config/_category_.json
  doc/docs/server_config/game-support-igdb.md
  doc/docs/server_config/img/twitch-register-app.png
  doc/docs/server_config/img/watcharr-game-details.png
  doc/docs/server_config/img/watcharr-settings-dropdown.png
  doc/docs/server_config/img/watcharr-twitch-config.png
  doc/docs/server_config/img/watcharr-twitch-service.png
  doc/docusaurus.config.js
  doc/package-lock.json
  doc/package.json
Labels: documentation

#344 TwitchModal: Add link to setup docs.
  src/routes/(app)/server/modals/TwitchModal.svelte
Labels: enhancement

#363 Ratings and Statuses for episodes
  server/activity.go
  server/routes.go
  server/watcharr.go
  server/watched.go
  server/watched_episodes.go
  server/watched_seasons.go
  src/lib/Activity.svelte
  src/lib/SeasonsList.svelte
  src/lib/SeasonsListEpisode.svelte
  src/lib/WatchedList.svelte
  src/lib/poster/PosterRating.svelte
  src/lib/util/helpers.ts
  src/types.ts
Labels: enhancement

#365 Fix discovery (trending) requests
  server/content.go
Labels: bug

#366 Issue #61
  .gitignore
  server/activity.go
  server/content.go
  server/routes.go
  src/lib/Activity.svelte
  src/lib/ActivityEditor.svelte
  src/lib/Modal.svelte
  src/lib/util/api.ts
  src/norm.scss
  src/routes/(app)/game/[id]/+page.svelte
  src/routes/(app)/movie/[id]/+page.svelte
  src/routes/(app)/tv/[id]/+page.svelte
  src/types.ts
Labels: enhancement
