Repository sbondCo/Watcharr, pull requests merged in 2024-09, with the labels that each got.

#627 New rating systems
  server/auth.go
  server/follow.go
  server/games.go
  server/import.go
  server/import_trakt.go
  server/plex_sync.go
  server/user.go
  server/watched.go
  src/lib/Icon.svelte
  src/lib/Rating.svelte
  src/lib/poster/ExtraDetails.svelte
  src/lib/poster/GamePoster.svelte
  src/lib/poster/Poster.svelte
  src/lib/poster/PosterRating.svelte
  src/lib/rating/Rating.svelte
  src/lib/rating/RatingSetting.svelte
  src/lib/rating/StarRating.svelte
  src/lib/rating/ThumbRating.svelte
  src/lib/rating/helpers.ts
  src/lib/settings/Setting.svelte
  src/lib/util/helpers.ts
  src/routes/(app)/game/[id]/+page.svelte
  src/routes/(app)/movie/[id]/+page.svelte
  src/routes/(app)/profile/+page.svelte
  src/routes/(app)/tv/[id]/+page.svelte
  src/types.ts
Labels: enhancement

#618 Import: add todomovies
  server/import.go
  server/tags.go
  src/lib/Icon.svelte
  src/routes/(app)/import/+page.svelte
  src/routes/(app)/import/process/+page.svelte
  src/store.ts
  src/types.ts
Labels: enhancement

#633 Fix no filtering tag page and other stuffs i found
  src/lib/Icon.svelte
  src/lib/WatchedList.svelte
  src/lib/nav/FilterMenu.svelte
  src/lib/tag/TagMenu.svelte
  src/routes/(app)/+layout.svelte
  src/routes/(app)/tag/[id]/+page.svelte
  src/store.ts
  src/types.ts
Labels: bug, enhancement

#634 test-pr.yml: Add format_check_go job
  .github/workflows/test-pr-server.yml
  .github/workflows/test-pr-web.yml
Labels: github_actions

#636 Fix tagmenu oob
  src/lib/actions/stayInView.ts
  src/lib/tag/TagMenu.svelte
  src/norm.scss
Labels: bug, enhancement
