Repository sbondCo/Watcharr, pull requests merged in 2025-05, with the labels that each got.

#883 doc: Add text-file, trakt, watcharr pages for importing.
  doc/docs/importing/myanimelist.md
  doc/docs/importing/text-file.md
  doc/docs/importing/trakt.md
  doc/docs/importing/watcharr.md
Labels: documentation

#862 Support for importing ryot 8 files
  src/routes/(app)/import/+page.svelte
Labels: bug

#822 feat(theme): add system preference handling to theme configuration
  src/lib/util/helpers.ts
  src/lib/util/theme.ts
  src/routes/(app)/profile/+page.svelte
  src/store.svelte.ts
  src/types.ts
Labels: enhancement

#886 Search shortcut & add missing keys that search handler should ignore
  src/routes/(app)/+layout.svelte
Labels: enhancement
